# デフォルトのスクリプト
# グローバルサーバー設定
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"

endpoints:
  - name: users
    versions:
      - version: v1
        method: GET
        path: /api/v1/users
        response:
          status: 200
          headers:
            Content-Type: application/json
          body: |
            {
              "users": [
                {"id": 1, "name": "Alice"},
                {"id": 2, "name": "Bob"}
              ]
            }
      - version: v2
        method: GET
        path: /api/v2/users
        response:
          status: 200
          headers:
            Content-Type: application/json
          body: |
            {
              "users": [
                {"id": 1, "name": "Alice", "role": "admin"},
                {"id": 2, "name": "Bob", "role": "user"}
              ]
            }
